# Generated by Django 4.1.4 on 2022-12-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_active_user_isactive_user_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_on',
        ),
    ]
