# Generated by Django 4.1.4 on 2023-10-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
