# Generated by Django 4.1.4 on 2023-10-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_author_alter_blog_description_blogip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogip',
            options={'verbose_name': 'Blog View'},
        ),
    ]
